# Generated by Django 5.1.7 on 2025-03-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=50)),
                ('email_user', models.EmailField(max_length=100)),
                ('password_user', models.CharField(max_length=100)),
                ('rol_user', models.CharField(choices=[('u', 'user')], max_length=1)),
                ('token_user', models.TextField()),
            ],
        ),
    ]
